### ISSUE TITLE
Add license file for next release

### ISSUE THREAD

**Issue by bsipocz** [conda-forge/regions-feedstock#1]
to make sure we don't forget it...

cc @mwcraig

**Comment by cdeil** [comment]
@bsipocz - Add license file where? What needs to be done here?

See  #5 for the v0.3 release.

**Comment by bsipocz** [comment]
Hmm, I can't remember, but let me try to figure it out and push to that PR.

**Comment by bsipocz** [comment]
The recipe looks very similar to the astropy one, so I'm not sure any more what I meant here. My best guess is that the license file was missing from the v0.2 release altogether and was added to the manifest after that release (https://github.com/astropy/regions/commit/1fd6713450c4983853ed852350ea67c20d4f2800). 

However, it's still not included in the released package but only in the source distribution. But that's a much wider issue affecting most of our packages (e.g. https://github.com/astropy/astropy/issues/7723), so I would rather close this this issue here assuming that when the linked issue above is addressed it will be addressed together for all the astropy coordinated packages including `regions`.
